root = ".."
testdata_dir = "web/testdata"
tmp_dir = "web/tmp"

[build]
  args_bin = ["-port", "8080"]
  bin = "./tmp/web-server.exe"
  cmd = "go build -o ./tmp/web-server.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "output", "examples", "web/tmp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["web", "pkg"]
  include_ext = ["go", "html", "js", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true 